spring:
  application:
    name: coupon-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: pdata@1234
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8083
